`timescale 1ns / 1fs
// =================================================================================
// lc_dco -- Behavioral LC-tank DCO
//
// This replaces the old NCO-based dco_nco (which needed a fixed physical
// "board_clk" to run its phase-accumulator at oversampled rate). A real LC DCO
// doesn't need any external clock at all -- it just free-runs at whatever
// instantaneous frequency its control word sets, and its edges ARE the clock.
// This model does the same thing directly in the time domain:
//
//   f_inst(t) = FREE_RUN_HZ + KDCO_HZ_PER_LSB * ctrl_word(t)
//
// dco_clk is generated by scheduling each half-period with a real-valued #delay
// recomputed from f_inst every half-cycle (zero-order-hold FM, same as a real
// DCO reacting to a new digital control word on the fly).
//
// dco_frac_gray reproduces what the old design's internal oversampled phase
// accumulator gave the TDC: a gray-coded fractional-phase word (0..2^FRAC_BITS-1)
// telling the TDC where inside the *current* DCO period "now" is. It's produced
// by a second, purely-internal self-timed process (no board clock, no port) that
// ticks at 2^FRAC_BITS x the current DCO rate -- an idealized stand-in for
// whatever fine-phase digitizer sits between the LC tank and the digital domain
// in real silicon.
//
// Not synthesizable -- this is a simulation-only stimulus/behavioral model.
// =================================================================================
module dco #(
    parameter real    FREE_RUN_HZ     = 70_000_000.0,  // f0 at ctrl_word = 0
    parameter real    KDCO_HZ_PER_LSB = 400.0,          // DCO gain (Hz / LSB of ctrl_word)
    parameter integer FRAC_BITS       = 7,               // fine-phase output width (matches digital_tdc)
    parameter real    MIN_HZ          = 1_000_000.0      // floor, guards against 0/negative freq in sim
)(
    input  wire                 rst,
    input  wire signed [15:0]   ctrl_word,
    output reg                  dco_clk,
    output reg  [FRAC_BITS-1:0] dco_frac_gray
);

    localparam integer OVERSAMPLE = (1 << FRAC_BITS);

    // Shared "what's the current period" state, written by the oscillator
    // process and read by the fine-phase process.
    real period_ns;
    real last_rise_time;

    // =============================================================
    // 1. Main oscillator -- the LC tank itself.
    // =============================================================
    initial begin
        dco_clk        = 1'b0;
        period_ns       = 1.0e9 / FREE_RUN_HZ;
        last_rise_time  = 0.0;
    end

    real f_inst;

    always begin
        if (rst) begin
            dco_clk   = 1'b0;
            period_ns = 1.0e9 / FREE_RUN_HZ;
            @(negedge rst);
        end else begin
            f_inst = FREE_RUN_HZ + KDCO_HZ_PER_LSB * ctrl_word;
            if (f_inst < MIN_HZ) f_inst = MIN_HZ;
            period_ns = 1.0e9 / f_inst;

            #(period_ns / 2.0);
            dco_clk = ~dco_clk;
            if (dco_clk) last_rise_time = $realtime;
        end
    end

    // =============================================================
    // 2. Fine-phase tracker -- idealized replacement for a TDC/ADC
    //    reading the tank's instantaneous phase. Self-ticks at
    //    OVERSAMPLE x f_inst, entirely internally.
    // =============================================================
    real    frac_real;
    integer frac_idx;
    reg [FRAC_BITS-1:0] frac_bin;

    initial dco_frac_gray = {FRAC_BITS{1'b0}};

    always begin
        if (rst) begin
            dco_frac_gray = {FRAC_BITS{1'b0}};
            @(negedge rst);
        end else begin
            #(period_ns / OVERSAMPLE);

            frac_real = (period_ns > 0.0) ? (($realtime - last_rise_time) / period_ns) : 0.0;
            if (frac_real >= 1.0) frac_real = 0.999999;
            if (frac_real < 0.0)  frac_real = 0.0;

            frac_idx = frac_real * OVERSAMPLE;
            if (frac_idx >= OVERSAMPLE) frac_idx = OVERSAMPLE - 1;

            frac_bin      = frac_idx[FRAC_BITS-1:0];
            dco_frac_gray = frac_bin ^ (frac_bin >> 1);   // binary -> gray, same as before
        end
    end

endmodule